# Generated by Django 5.2.7 on 2025-10-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
