# Generated by Django 5.2.7 on 2025-10-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_element_img_alter_element_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='img',
            new_name='imagen',
        ),
    ]
