# Generated by Django 5.2.7 on 2025-10-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_rename_img_element_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='imagen',
        ),
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='elements/'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
