# Generated by Django 5.2.7 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_element_imagen_element_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image1', models.ImageField(upload_to='carousel/')),
                ('image2', models.ImageField(upload_to='carousel/')),
                ('image3', models.ImageField(upload_to='carousel/')),
            ],
        ),
    ]
